env:
  es6: true
  node: true
  mocha: true

extends:
  - airbnb

rules:
  #Allow _id on mongo id attributes and rewire __get__
  no-underscore-dangle: [error, {allow: [_id, __get__]}]

  #Allow reassigning koa context
  no-param-reassign: off

  #Allow for of/in loops as forEach does not work with async await
  no-restricted-syntax: [warn, ForOfStatement, ForInStatement]

  #Ignore unused-var error message on chai.should()
  no-unused-vars: [error, {varsIgnorePattern: should}]

  #Allow devDependencies for tests
  import/no-extraneous-dependencies: [error, {devDependencies: ['**/*.test.js']}]
