language: node_js
node_js:
  - "node"
addons:
    code_climate:
        repo_token: b5beab30d6c5f64c881325111106a0e29ea3255f29736afa910974a2b9306c22
install:
  - npm install -g codeclimate-test-reporter
  - npm install
after_success:
  - codeclimate-test-reporter < lcov.info
